name: Build with Parameters

on:
  workflow_dispatch:
    inputs:
      parameter_one:
        description: 'Parameter One'
        required: true
      parameter_two:
        description: 'Parameter Two'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      PARAMETER_ONE: ${{ github.event.inputs.parameter_one }}
      PARAMETER_TWO: ${{ github.event.inputs.parameter_two }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Display parameters
      run: |
        import os
        print(os.environ['PATH'])
        para = "Parameter One: $PARAMETER_ONE \nParameter Two: $PARAMETER_TWO"
        print(para)
        with open('parameters.txt', 'w') as f:
            f.write(para)
      shell: python
       
    - name: Display parameter file
      run: cat parameters.txt

    # - name: Build
    #   run: |
    #     if [ "${{ runner.os }}" == "Windows" ]; then
    #       .\your-build-script.bat -ParamFile parameters.txt
    #     else
    #       ./your-build-script.sh -ParamFile parameters.txt
    #     fi
