name: BuildwithParameters
on:
  workflow_dispatch:
    inputs:
      parameter_one:
        description: 'Parameter One'
        required: true
      parameter_two:
        description: 'Parameter Two'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        parameter_one: [${{ github.event.inputs.parameter_one }}]
        parameter_two: [${{ github.event.inputs.parameter_two }}]  
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display parameters
      run: |
        echo "Parameter One: ${{ matrix.parameter_one }}"
        echo "Parameter Two: ${{ matrix.parameter_two }}"

    - name: Create parameter file
      run: |
        echo "Parameter One: ${{ matrix.parameter_one }}" > parameters.txt
        echo "Parameter Two: ${{ matrix.parameter_two }}" >> parameters.txt

    - name: Display parameter file
      run: cat parameters.txt

    # - name: Build
    #   run: |
    #     if [ "$RUNNER_OS" == "Windows" ]; then
    #       .\your-build-script.bat -ParamFile parameters.txt
    #     else
    #       ./your-build-script.sh -ParamFile parameters.txt
    #     fi
